kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  persistentClassName: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
